os: linux
language: node_js
node_js:
  - "11"
sudo: true
services: 
  - docker

before_install:
  - docker build -t nawinest/reactjs-with-dockers -f Dockerfile.dev .

script:
  - docker run -e CI=true nawinest/reactjs-with-dockers npm run test